### GET Carts
GET http://localhost:8080/api/carts/
Accept: application/json

### GET Carts With Filter
GET http://localhost:8080/api/carts/?page=0&size=10&sort=cartId,desc
Accept: application/json

### GET Cart By Id
GET http://localhost:8080/api/carts/1
Accept: application/json

### GET Cart By User Id
GET http://localhost:8080/api/carts/user/1
Accept: application/json

### POST Cart
POST http://localhost:8080/api/carts/
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 2,
      "discount": 50
    },
    {
      "productId": 2,
      "quantity": 1,
      "discount": 50
    },
    {
      "productId": 3,
      "quantity": 1,
      "discount": 50
    }
  ]
}

### PUT Cart
PUT http://localhost:8080/api/carts/1
Content-Type: application/json
Accept: application/json

{
  "merge": true,
  "items": [
    {
      "productId": 2,
      "quantity": 2,
      "discount": 50
    }
  ]
}

### DELETE Cart
DELETE http://localhost:8080/api/carts/1
Accept: application/json

### POST Checkout
POST http://localhost:8080/api/carts/1/checkout
Content-Type: application/json
Accept: application/json

{
  "productIds": [
    1,
    2
  ]
}
