ALTER TABLE oe.categories
    ADD COLUMN created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE oe.categories
    ADD COLUMN modified_date TIMESTAMP;

ALTER TABLE oe.suppliers
    ADD COLUMN created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE oe.suppliers
    ADD COLUMN modified_date TIMESTAMP;

ALTER TABLE oe.shippers
    ADD COLUMN created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE oe.shippers
    ADD COLUMN modified_date TIMESTAMP;
